### ISSUE TITLE
Create release version

### ISSUE THREAD

**Issue by Invictaz** [G2-Games/sixaxis-pair_rs#1]
Hello, can you create a release version? I found out it written in the Rust language but I cannot compile your code yet.
Maybe you can assist me for a Windows version?

I tried installing Rust on Windows but it requires more than 5GB of Visual Studio installation

![image](https://github.com/G2-Games/sixaxis-pair_rs/assets/20338545/d4398149-4042-409a-9764-35e4fbfc6906)

**Comment by G2-Games** [comment]
I created a release with binaries for several different architectures and operating systems... I also fixed my code :sweat_smile: 

Let me know if something doesn't work.
