### ISSUE TITLE
Dualshock 3 not detected

### ISSUE THREAD

**Issue by Invictaz** [G2-Games/sixaxis-pair_rs#2]
It is detected by the old sixaxispairtool which users libusb.
So I don't know why it doesn't work in your software.
Windows 11 64 bit.

Maybe a special driver is needed?

![image](https://github.com/G2-Games/sixaxis-pair_rs/assets/20338545/6fdeb036-ba02-40d3-8ddc-b2c03f747cd6)

EDIT:

Even with the official drivers from Sony it doesn't work
See https://community.pcgamingwiki.com/files/file/2854-sce-wireless-controller-driver-v3000-official-drivers-for-dualshock-3/

![image](https://github.com/G2-Games/sixaxis-pair_rs/assets/20338545/27a27127-0a91-49ac-bfe4-0173e33cd194)

**Comment by G2-Games** [comment]
I think this is happening because the controller is using either LibUSB or a USB HID driver, while generic device access requires WinUSB. I don't have enough windows experience to be able to fix this, but a solution may be to use a tool like [Zadig](https://zadig.akeo.ie/) to switch the driver to WinUSB from whatever it is at the moment.

**Comment by Invictaz** [comment]
It's weird that with SixaxisPairtool libusb is required and with yours another driver.

The official Sony driver should however work with no questions. 

On your request I tried with Winusb. It does work then.
Continuously switching drivers (with Zadig taking upto 5 mins per switch) is quite impractical. 

![image](https://github.com/G2-Games/sixaxis-pair_rs/assets/20338545/bdf778d9-99c7-4186-8c61-2c7aa38e97cf)

![image](https://github.com/G2-Games/sixaxis-pair_rs/assets/20338545/595cea5f-a4fb-4458-b4ee-746577323098)

**Comment by G2-Games** [comment]
Due to how this program works that is the only solution. I do not have time to dedicate to improving this at the moment, it is uploaded in the hope it will be useful. I am open to pull requests with improvements, however.

**Comment by Invictaz** [comment]
I really appreciate the effort 😄
Sadly I don't have coding skills in Rust
